apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "srevox.fullname" . }}-activity
  labels:
    {{- include "srevox.labels" . | nindent 4 }}
    app.kubernetes.io/component: activity
spec:
  replicas: {{ .Values.activity.replicaCount }}
  selector:
    matchLabels:
      {{- include "srevox.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: activity
  template:
    metadata:
      labels:
        {{- include "srevox.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: activity
    spec:
      containers:
        - name: activity
          image: "{{ .Values.activity.image }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5005
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "srevox.fullname" . }}-config
            - secretRef:
                name: {{ include "srevox.fullname" . }}-secrets
          resources:
            {{- toYaml .Values.activity.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "srevox.fullname" . }}-activity
  labels:
    {{- include "srevox.labels" . | nindent 4 }}
    app.kubernetes.io/component: activity
spec:
  type: ClusterIP
  ports:
    - port: 5005
      targetPort: 5005
      protocol: TCP
      name: http
  selector:
    {{- include "srevox.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: activity
