apiVersion: v1
kind: Secret
metadata:
  name: {{ include "srevox.fullname" . }}-secrets
  labels:
    {{- include "srevox.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
  BACKEND_SECRET_KEY: {{ .Values.global.backendSecretKey | quote }}
  ENCRYPTION_KEY: {{ .Values.global.encryptionKey | quote }}
