apiVersion: v2
name: srevox
description: Srevox - Enterprise Site Reliability Engineering (SRE) & Incident Intelligence Platform
type: application
version: 1.0.0
appVersion: 1.0.0
keywords:
  - sre
  - observability
  - monitoring
  - incidents
  - kubernetes
maintainers:
  - name: Srevox Engineering
    email: support@srevox.com
